### ISSUE TITLE
Undo processing on bitmap

### ISSUE THREAD

**Issue by num0005** [Himanshu-01/H2PC_TagExtraction#23]
Copied from #10

* Appears to be missing bitmap data a majority of the time among other things. Seems to be an issue with the extractor not loading the resource maps. Fixed by 0600328

* Has issues beyond this where even if the bitmap data is internal then it may not be written for whatever reason.

* Something is preventing them from being compressed in H2Tool. This means that extracted bitmaps can't be reused until the cause is found and fixed. Worked around by Project-Cartographer/H2Codez@f4adbbc

**Comment by General-101** [comment]
Point two not happening as of commit https://github.com/Project-Cartographer/H2PC_TagExtraction/commit/0600328297ff22d1ff6fb95d4619c0a90c3d721c so it was probably resource map related too and I just guessed wrong.

**Comment by num0005** [comment]
Project-Cartographer/H2Codez@5c0d439c21895218a47179af42826519e1a819a6 is another work around
